package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	dbmodel "skeleton-service/database/model"
	"skeleton-service/graph/model"

	"go.uber.org/zap"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	r.Logger.Info("createTodo", zap.Any("input", input))
	newTodo := dbmodel.Todo{Text: input.Text, UserID: input.UserID, Done: false}
	result := r.DB.Create(&newTodo)

	if result.Error != nil {
		r.Logger.Error("failed to create todo", zap.Error(result.Error))
		return nil, result.Error
	}

	return convertDBTodoToModel(&newTodo), nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	r.Logger.Info("todos")
	var dbTodos []dbmodel.Todo
	result := r.DB.Find(&dbTodos)
	if result.Error != nil {
		return nil, result.Error
	}

	var todos []*model.Todo
	for _, dbTodo := range dbTodos {
		todos = append(todos, convertDBTodoToModel(&dbTodo))
	}

	return todos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func convertDBTodoToModel(dbTodo *dbmodel.Todo) *model.Todo {
	return &model.Todo{
		ID:   dbTodo.ID,
		Text: dbTodo.Text,
		Done: dbTodo.Done,
		User: &model.User{ID: dbTodo.UserID, Name: "Test User"},
	}
}
